use_frameworks!

platform :ios, '9.0'

target 'ZSTabPageView-Objc_Example' do
  pod 'ZSTabPageView-Objc', :path => '../'

  target 'ZSTabPageView-Objc_Tests' do
    inherit! :search_paths

    
  end
end
